project: 
  resources: ["images"]
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "!readme.md"
  - "!gitpushnotes.md"


website:
  title: "Eduardo Ramirez"
  favicon: images/favicon.png
  site-url: https://1ramirez7.github.io/
  back-to-top-navigation: true
  repo-url: https://github.com/1Ramirez7/1ramirez7.github.io

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      - text: "GitHub"
        icon: github
        href: "https://github.com/1Ramirez7"
      - text: LinkedIn
        icon: linkedin
        href: https://www.linkedin.com/in/ramirez-eduardo1/
      - text: Resume
        icon: file-text
        href: "resume.pdf"
      - text: Email
        icon: envelope
        href: mailto:eduardo.er.ramirez@Gmail.com
        # https://quarto.org/docs/websites/website-listings.html
      
  page-footer: 
    border: true
    left: "Eduardo Ramirez 2025©"
    right: 
      - icon: linkedin
        href: "www.linkedin.com/in/eduardo-ramirez-lds"

format:  
  html:
    theme: #(https://quarto.org/docs/output-formats/html-themes.html)
      light: flatly 
      dark: darkly
    css: styles.css
    toc: true


