project: 
  type: website
  output-dir: docs  
website:
  title: "Eduardo I Ramirez Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://1ramirez7.github.io/Portfolio_
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Eduardo I Ramirez 2024©"
    right: 
      - icon: linkedin
        href: linkedin.com/in/eduardo-ramirez-lds

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "My Resume"
        file: resume.qmd
      # - text: "Data Cleansing"
      #   file: cleansing.qmd
      # - text: "Story Telling"
      #   file: story_telling.qmd
      # - text: "Machine Learning"
      #   file: ml.qmd
      
  sidebar:
    - title: "Projects"
      style: "docked"
      background: light
      contents:
        - text: "Projects"
          file: projects.qmd
        - text: "Project 1"
          file: Projects/project1.qmd
        - text: "RDUS Capital Structure Analysis"
          file: Projects/RDUS Capital Structure Analysis.qmd
        - text: "RDUS Capital Structure Analysis #2"
          file: Projects/term2.qmd
        - text: "RDUS Statistical Research (OLS)"
          file: Projects/term2.qmd
        - text: "---"
        #continue the pattern if you need more links
        #copy paste from title and keep it indented to sidebar to add additonal sidebar navigation for other pages

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
