project: 
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "!readme.md"
  - "!gitpushnotes.md"


website:
  title: "Eduardo Ramirez"
  favicon: Images/favicon.png
  site-url: https://1ramirez7.github.io/
  back-to-top-navigation: true
  repo-url: https://github.com/1Ramirez7/1ramirez7.github.io

  page-footer: 
    border: true
    left: "Eduardo Ramirez 2025©"
    right: 
      - icon: linkedin
        href: "www.linkedin.com/in/eduardo-ramirez-lds"


  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "My Resume"
        file: resume.qmd
      
format:  
  html:
    theme: #(https://quarto.org/docs/output-formats/html-themes.html)
      light: flatly 
      dark: darkly
    css: styles.css
    toc: true
